# Generated by Django 5.1.1 on 2024-09-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='calendar_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_management.calendarevent'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave_management.leavesummary'),
        ),
    ]
