# Generated by Django 5.1.1 on 2024-09-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_alter_calendarevent_leave_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='leave_request',
        ),
        migrations.RemoveField(
            model_name='leavesummary',
            name='leave_request',
        ),
    ]
